import { useRef, Suspense, useEffect } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Text, Stars, Environment } from '@react-three/drei';
import * as THREE from 'three';
import { useGameStore } from '../store';
import { GLTFModel } from './ModelLoader';
import { BulletRenderer, fireShot } from './BulletSystem';
import { createAnimState, updateProceduralAnim, triggerShoot, triggerHit, triggerDeath, triggerAttack, triggerStagger, type AnimState } from './ProceduralAnim';
import { ScreenShake, DamageNumbers } from './VFX';
import { PostFX } from './PostFX';
import { WeaponView } from './WeaponSystem';
import { audioManager } from '../audio/AudioManager';
import FullTerrain from '../terrain/TerrainMesh';
// ===== New Engine Systems =====
import { inputManager } from '../player/InputManager';
import { cameraControllerTick } from '../player/CameraController';
import { weaponManagerTick, getCrosshairSpread } from '../weapons/WeaponManager';
import { tickDayNight, getSunPosition, getAmbientIntensity, getSunIntensity, getFogColor } from '../survival/DayNightCycle';
import { MagicSystem } from '../weapons/MagicProjectile';
import { SkillEffects, type SkillEffectsHandle } from '../weapons/SkillEffects';
import { Arrow, type ArrowData } from '../weapons/Arrow';
import { LootChest } from '../world/LootChest';
import { ScenePortal } from '../scenes/ScenePortal';
import { getWeaponConfig, isRangedWeapon, isMeleeWeapon } from '../weapons/WeaponConfig';
import { tickProjectileHits, applyMeleeDamage, applySkillDamage } from '../combat/ProjectileHitSystem';
import { SPELLS } from '../content/spells';
import type { MagicProjectileState } from '../weapons/MagicProjectile';
import { getComboStep } from '../weapons/WeaponManager';
import { getYaw } from '../player/CameraController';
import { UNIT_REGISTRY } from '../units/UnitRegistry';
import { UnitCharacter } from '../units/UnitCharacter';
import { BulletDecals } from './BulletDecals';
import { ExplosionSystem } from '../vfx/Explosion';
import { MuzzleFlashSystem, triggerMuzzleFlash } from '../vfx/MuzzleFlash';
import { GrenadeRenderer, createGrenadeFromCamera, type GrenadeData } from '../weapons/Grenade';
// grenadeInput alias removed — inputManager already imported above
